
export const CITIES = [
  { id: 'agra', name: 'Agra', state: 'Uttar Pradesh', active: true },
  { id: 'delhi', name: 'Delhi NCR', state: 'Delhi', active: true },
  { id: 'noida', name: 'Noida', state: 'Uttar Pradesh', active: true },
  { id: 'gurgaon', name: 'Gurgaon', state: 'Haryana', active: true },
  { id: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', active: true },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', active: true },
  { id: 'kanpur', name: 'Kanpur', state: 'Uttar Pradesh', active: true },
  { id: 'mathura', name: 'Mathura', state: 'Uttar Pradesh', active: true },
];

export const CATEGORIES = [
  {
    id: 'cat-laptop-computer', slug: 'laptop-and-computer', name: 'Laptop & Computer',
    icon: 'Laptop', description: 'Laptop repairs, software help, upgrades and home network setup',
    color: '#2563EB', bgPastel: '#DBEAFE',
    image: '/service-images/computers.svg', servicesCount: 0,
  },
  {
    id: 'cat-electronics', slug: 'electronics', name: 'Electronics',
    icon: 'Tv', description: 'Mobile, TV, security camera and smart home assistance',
    color: '#7C3AED', bgPastel: '#EDE9FE',
    image: '/service-images/electronics.svg', servicesCount: 0,
  },
  {
    id: 'cat-ac-appliances',
    slug: 'ac-and-appliances',
    name: 'AC & Appliances',
    icon: 'AirVent',
    description: 'Jet pump servicing, gas charging, refrigerator & washing machine repair',
    color: '#FF7A00',
    bgPastel: '#FFF1E5',
    badge: 'Popular',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    servicesCount: 14,
  },
  {
    id: 'cat-cleaning',
    slug: 'cleaning-and-pest',
    name: 'Home Cleaning',
    icon: 'Sparkles',
    description: 'Deep bathroom, kitchen, sofa shampooing & hospital-grade termite control',
    color: '#FF7A00',
    bgPastel: '#FFF1E5',
    badge: 'Trending',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    servicesCount: 18,
  },
  {
    id: 'cat-beauty',
    slug: 'beauty-and-wellness',
    name: 'Beauty & Salon',
    icon: 'Scissors',
    description: 'Salon at home for women & men, facials, waxing, pedicure & reflexology',
    color: '#EC4899',
    bgPastel: '#FCE7F3',
    badge: 'Best Rated',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    servicesCount: 22,
  },
  {
    id: 'cat-electrician',
    slug: 'electrician-and-repairs',
    name: 'Electrician',
    icon: 'Zap',
    description: 'Switchboard fixes, inverter setup, ceiling fan installation & wiring',
    color: '#F59E0B',
    bgPastel: '#FEF3C7',
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
    servicesCount: 16,
  },
  {
    id: 'cat-plumber',
    slug: 'plumbing-services',
    name: 'Plumbing',
    icon: 'Wrench',
    description: 'Leak detection, tap & mixer installation, drainage clearing & geysers',
    color: '#3B82F6',
    bgPastel: '#DBEAFE',
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    servicesCount: 12,
  },
  {
    id: 'cat-carpenter',
    slug: 'carpentry-and-furniture',
    name: 'Carpentry',
    icon: 'Hammer',
    description: 'Modular furniture assembly, door locks, hinges & customized wood repairs',
    color: '#8B5CF6',
    bgPastel: '#EDE9FE',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
    servicesCount: 9,
  },
  {
    id: 'cat-pest-control',
    slug: 'pest-control',
    name: 'Pest Control',
    icon: 'ShieldAlert',
    description: 'Herbal odorless gel for cockroaches, anti-termite shield & bed bug removal',
    color: '#10B8A8',
    bgPastel: '#CCFBF1',
    badge: 'Warranty',
    image: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80',
    servicesCount: 8,
  },
  {
    id: 'cat-painting',
    slug: 'painting-and-waterproofing',
    name: 'Painting & Walls',
    icon: 'Paintbrush',
    description: 'Full home whitewash, waterproof wall coatings, texture accent walls',
    color: '#FF7A00',
    bgPastel: '#FFF1E5',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    servicesCount: 10,
  },
  {
    id: 'cat-moving',
    slug: 'packers-and-movers',
    name: 'Packers & Movers',
    icon: 'Truck',
    description: 'Local and inter-city hassle-free relocation with bubble wrap protection',
    color: '#F97316',
    bgPastel: '#FFEDD5',
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    servicesCount: 6,
  },
  {
    id: 'cat-appliance-repair',
    slug: 'appliance-repair',
    name: 'Appliance Repair',
    icon: 'Wrench',
    description: 'Washing machine, refrigerator, microwave & kitchen chimney repair',
    color: '#E85D04',
    bgPastel: '#FFF1E5',
    badge: 'Same Day',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    servicesCount: 12,
  },
  {
    id: 'cat-bathroom-cleaning',
    slug: 'bathroom-cleaning',
    name: 'Bathroom Cleaning',
    icon: 'Sparkles',
    description: 'Intense hard water stain removal, descaling, tile scrubbing & sanitization',
    color: '#3B82F6',
    bgPastel: '#DBEAFE',
    badge: 'Popular',
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    servicesCount: 8,
  },
  {
    id: 'cat-sofa-cleaning',
    slug: 'sofa-cleaning',
    name: 'Sofa Cleaning',
    icon: 'Sofa',
    description: 'Deep foam shampooing and extraction for fabric & leather sofas',
    color: '#8B5CF6',
    bgPastel: '#EDE9FE',
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&q=80',
    servicesCount: 7,
  },
  {
    id: 'cat-water-purifier',
    slug: 'water-purifier',
    name: 'Water Purifier',
    icon: 'Droplet',
    description: 'RO service, membrane filter replacement & TDS water purity check',
    color: '#0EA5E9',
    bgPastel: '#E0F2FE',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80',
    servicesCount: 6,
  },
  {
    id: 'cat-laptop-electronics',
    slug: 'laptop-and-electronics',
    name: 'Laptop & Electronics',
    icon: 'Laptop',
    description: 'Doorstep diagnosis, screen repair, battery replacement & OS fix',
    color: '#6366F1',
    bgPastel: '#EEF2FF',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    servicesCount: 8,
  },
  {
    id: 'cat-home-improvement',
    slug: 'home-improvement',
    name: 'Home Improvement',
    icon: 'Home',
    description: 'Modular interior upgrades, false ceiling, lighting & aesthetic repairs',
    color: '#FF7A00',
    bgPastel: '#FFF1E5',
    badge: 'Premium',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    servicesCount: 11,
  },
];

export const PROFESSIONALS = [
  {
    id: 'pro-rahul',
    name: 'Rahul Sharma',
    phone: '+91 98765 43210',
    email: 'rahul.technician@serviceassist.in',
    profession: 'Senior HVAC & AC Specialist',
    categoryId: 'cat-ac-appliances',
    rating: 4.9,
    reviewsCount: 1240,
    completedJobs: 1380,
    experienceYears: 7,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    bio: 'Certified Daikin & Voltas refrigeration engineer with over 7 years in split and window AC deep jet cleaning, inverter diagnosis, and zero-mess service.',
    skills: ['Jet Foam Cleansing', 'Gas Pressure Check', 'PCB Diagnostic', 'Inverter AC Troubleshooting'],
    certifications: ['National Skill Development Certificate - HVAC Grade A', 'Service Assist Verified Master Partner'],
    languages: ['Hindi', 'English'],
    serviceAreas: ['Agra', 'Delhi NCR', 'Noida', 'Gurgaon'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '08:00 AM - 08:00 PM',
    isAvailableToday: true,
  },
  {
    id: 'pro-priya',
    name: 'Priya Verma',
    phone: '+91 98111 22334',
    email: 'priya.salon@serviceassist.in',
    profession: 'Lead Aesthetician & Hair Stylist',
    categoryId: 'cat-beauty',
    rating: 4.95,
    reviewsCount: 890,
    completedJobs: 980,
    experienceYears: 6,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    bio: 'Former Lakmé senior trainer specializing in organic facials, painless roll-on waxing, bridal styling, and relaxing head acupressure.',
    skills: ['O3+ Hydra Facial', 'Rica Brazilian Waxing', 'L’Oréal Spa', 'Bridal Makeover'],
    certifications: ['VLCC Advanced Cosmetology', 'CIDESCO Certified Aesthetician'],
    languages: ['Hindi', 'English'],
    serviceAreas: ['Agra', 'Delhi NCR', 'Jaipur', 'Lucknow'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Fri', 'Sat', 'Sun'],
    workingHours: '09:00 AM - 07:30 PM',
    isAvailableToday: true,
  },
  {
    id: 'pro-amit',
    name: 'Amit Rawat',
    phone: '+91 97123 99887',
    email: 'amit.cleaning@serviceassist.in',
    profession: 'Deep Cleaning Master Crew Lead',
    categoryId: 'cat-cleaning',
    rating: 4.88,
    reviewsCount: 1650,
    completedJobs: 1820,
    experienceYears: 8,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Equipped with industrial Taski equipment, eco-certified chemicals, and German steam vacs for spotless bathroom descaling and sofa restoration.',
    skills: ['Taski Single Disc Scrubbing', 'Karcher Steam Sanitization', 'Fabric Extraction', 'Tile Grout Cleansing'],
    certifications: ['ISO 9001 Hygiene & Sanitation Specialist'],
    languages: ['Hindi', 'Punjabi'],
    serviceAreas: ['Agra', 'Delhi NCR', 'Noida', 'Gurgaon', 'Mathura'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    workingHours: '07:30 AM - 07:00 PM',
    isAvailableToday: true,
  },
  {
    id: 'pro-vikram',
    name: 'Vikram Singh',
    phone: '+91 99234 55667',
    email: 'vikram.electrician@serviceassist.in',
    profession: 'Licensed Master Electrician',
    categoryId: 'cat-electrician',
    rating: 4.86,
    reviewsCount: 1120,
    completedJobs: 1400,
    experienceYears: 9,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Government certified Grade 1 electrician with experience in high voltage domestic circuit breakers, smart home switches, and shock-prevention testing.',
    skills: ['MCB & Distribution Boards', 'Inverter Wiring', 'Smart Switch Integration', 'Concealed Conduit Repairs'],
    certifications: ['State Electrical Supervisory License', 'Bureau of Energy Efficiency Auditor'],
    languages: ['Hindi', 'English'],
    serviceAreas: ['Agra', 'Delhi NCR', 'Lucknow', 'Kanpur'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    workingHours: '08:00 AM - 09:00 PM',
    isAvailableToday: true,
  },
  {
    id: 'pro-manoj',
    name: 'Manoj Kumar',
    phone: '+91 98450 12345',
    email: 'manoj.plumbing@serviceassist.in',
    profession: 'Sanitary & Pressure Line Plumber',
    categoryId: 'cat-plumber',
    rating: 4.82,
    reviewsCount: 940,
    completedJobs: 1100,
    experienceYears: 6,
    verified: true,
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    bio: 'Expert in modern CP fittings (Jaquar, Kohler, Grohe), pressurized lines, concealed pipe leaks, and instant water heater servicing.',
    skills: ['CP Fittings Replacement', 'Pressure Motor Setup', 'Drain Spiral Augering', 'Geyser Thermal Cutout'],
    certifications: ['Indian Plumbing Association Certified'],
    languages: ['Hindi'],
    serviceAreas: ['Agra', 'Delhi NCR', 'Noida', 'Gurgaon'],
    availableDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    workingHours: '08:00 AM - 08:30 PM',
    isAvailableToday: true,
  },
];

export const SERVICES = [
  {
    id: 'srv-ac-foamjet',
    slug: 'ac-jet-service',
    name: 'Foam Jet Power AC Servicing',
    categoryId: 'cat-ac-appliances',
    categoryName: 'AC & Appliances',
    rating: 4.88,
    reviewsCount: 14200,
    startingPrice: 599,
    originalPrice: 899,
    durationMin: 45,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Deep foam cleaning of indoor cooling coils + high pressure jet pump spray for 2x faster cooling.',
    description: 'Revive your split or window air conditioner with our proprietary dual-foam technology. Eliminates accumulated dust, allergens, bacteria, and improves cooling efficiency while reducing electricity consumption by up to 25%.',
    popular: true,
    trending: true,
    recommendedReason: 'Recommended for hot seasons to boost cooling efficiency and reduce electricity bills',
    variants: [
      {
        id: 'var-split-1',
        name: 'Split AC Power Jet Clean (1 Unit)',
        price: 599,
        originalPrice: 899,
        durationMin: 45,
        description: 'Complete indoor jet foam cleaning + outdoor unit pressure wash + anti-bacterial coating.',
        included: ['Indoor coil foam spray', 'Jet pump wash', 'Drain pipe clearing', 'Gas pressure check', 'Filter sanitize'],
      },
      {
        id: 'var-split-2',
        name: 'Split AC Dual Combo (2 Units)',
        price: 1099,
        originalPrice: 1798,
        durationMin: 80,
        description: 'Comprehensive jet service for 2 Split ACs. Best value for master bedroom and living room.',
        included: ['Both indoor units foam jet wash', 'Both outdoor compressors cleaned', 'Gas pressure report', '30-day service warranty'],
      },
      {
        id: 'var-window-1',
        name: 'Window AC Deep Descaling',
        price: 499,
        originalPrice: 749,
        durationMin: 40,
        description: 'Full unmounting, high-pressure coil wash, tray descaling and re-installation.',
        included: ['Machine extraction', 'Tray wash', 'Motor lubrication check', 'Temp check test'],
      },
    ],
    whatIncluded: [
      'Indoor cooling coil foam cleaning with non-corrosive chemical',
      'High-pressure water jet spray of blower fan & drain tray',
      'Outdoor condenser unit pressure wash',
      'Gas leak detection & operating pressure check',
      'Pre & post service temperature check',
      'Mess-free catch jacket to protect walls and floor',
    ],
    whatExcluded: [
      'Cost of spare parts or capacitor replacement if faulty',
      'Refrigerant / Gas refill (available as an add-on)',
      'Masonry or carpentry repairs',
    ],
    whyChoose: [
      'Increases cooling airflow by up to 40%',
      'Saves up to ₹1,200 on monthly power bills',
      '30-day no-questions-asked service guarantee',
      'Verified technicians with 5+ years experience',
    ],
    faqs: [
      {
        question: 'Will the water make a mess on my bedroom wall?',
        answer: 'Not at all! Our technician uses a specialized waterproof spill jacket with a drainage funnel pipe directly into a bucket.',
      },
      {
        question: 'How often should I get my AC jet serviced?',
        answer: 'We recommend servicing before the summer peak and once mid-season for optimal cooling and lower power bills.',
      },
      {
        question: 'Does this service include gas refill?',
        answer: 'The service includes a complimentary gas pressure check. If refrigerant is low, the technician will diagnose leaks and top up gas upon your approval at standardized rate-card pricing.',
      },
    ],
  },
  {
    id: 'srv-bathroom-deep',
    slug: 'bathroom-deep-cleaning',
    name: 'Intense Bathroom Deep Cleansing',
    categoryId: 'cat-cleaning',
    categoryName: 'Cleaning & Pest Control',
    rating: 4.84,
    reviewsCount: 18450,
    startingPrice: 449,
    originalPrice: 699,
    durationMin: 60,
    image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Hard water stain removal from tiles & glass, descaling of taps, WC sanitization & grout scrubbing.',
    description: 'Transform stained tiles, cloudy glass partitions, and scaled taps into sparkling sanitary perfection. We utilize non-toxic acid-free chemicals that restore shine without eroding tile grout or chrome finishes.',
    popular: true,
    trending: false,
    recommendedReason: 'Top booked service in your city for hard water scale removal',
    variants: [
      {
        id: 'var-bath-1',
        name: 'Single Bathroom Complete Scrub',
        price: 449,
        originalPrice: 699,
        durationMin: 60,
        description: 'Ideal for 1 master or guest bathroom with severe hard-water stains.',
        included: ['Wall & floor tile rotary scrub', 'Glass partition descaling', 'WC & washbasin sanitization', 'Mirror & fitting polish'],
      },
      {
        id: 'var-bath-2',
        name: '2 Bathrooms Refresh Pack',
        price: 799,
        originalPrice: 1398,
        durationMin: 110,
        description: 'Deep hygiene scrub for two bathrooms at a bundled discount.',
        included: ['Full scrub for 2 bathrooms', 'Anti-fungal treatment', 'Exhaust & geyser outer wipe'],
      },
      {
        id: 'var-bath-3',
        name: '3 Bathrooms Whole House Pack',
        price: 1149,
        originalPrice: 2097,
        durationMin: 150,
        description: 'Complete sanitary treatment for 3 bathrooms.',
        included: ['All 3 bathrooms deep scrubbed', 'Floor buffing', 'Drainage de-clogging check'],
      },
    ],
    whatIncluded: [
      'Chemical descaling of hard water deposits on wall & floor tiles',
      'Shower glass panel stain extraction',
      'Toilet bowl (WC), bidet, and washbasin sanitization with hospital-grade disinfectant',
      'Mirror cleaning & chrome tap buffing',
      'Exhaust fan outer blade degreasing',
    ],
    whatExcluded: [
      'Ceiling paint peel restoration',
      'Unclogging severe main line blockages',
    ],
    whyChoose: [
      'Acid-free formulas protect expensive Jaquar & Kohler fixtures',
      'Removes up to 99.9% mildew and bacteria',
      'Eco-friendly child & pet safe hygiene chemicals',
    ],
    faqs: [
      {
        question: 'Do your chemicals damage chrome taps or marble tiles?',
        answer: 'No, we never use raw hydrochloric acid. We use mild alkaline and enzymatic cleaners specifically formulated for CP fittings and natural stone.',
      },
      {
        question: 'Do I need to supply buckets, mops, or cloths?',
        answer: 'No, our professionals carry their complete kit including microfiber cloths, scrubbers, steampads, and wipers.',
      },
    ],
  },
  {
    id: 'srv-salon-women',
    slug: 'salon-at-home-women',
    name: 'Glow & Relax Salon Package for Women',
    categoryId: 'cat-beauty',
    categoryName: 'Beauty & Salon',
    rating: 4.92,
    reviewsCount: 21300,
    startingPrice: 899,
    originalPrice: 1499,
    durationMin: 90,
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'O3+ Facial, honey chocolate waxing, classic pedicure, and threading in the comfort of home.',
    description: 'Indulge in a premium parlor experience without stepping outside. Our certified beauticians arrive with sanitized disposable sheets, sealed branded product pouches, and soothing spa music.',
    popular: true,
    trending: true,
    recommendedReason: 'Top rated by women in your neighborhood for hygiene and organic treatments',
    variants: [
      {
        id: 'var-salon-glow',
        name: 'Radiance Glow Combo (Facial + Waxing)',
        price: 899,
        originalPrice: 1499,
        durationMin: 75,
        description: 'Diamond brightening facial + full arms & underarms honey waxing + eyebrow shaping.',
        included: ['Diamond Facial', 'Full arms honey wax', 'Underarms wax', 'Eyebrow & upper lip threading'],
      },
      {
        id: 'var-salon-headtoeto',
        name: 'Deluxe Head-to-Toe Pampering',
        price: 1599,
        originalPrice: 2499,
        durationMin: 120,
        description: 'O3+ Gold peel facial + full legs & arms waxing + rose pedicure & manicure.',
        included: ['O3+ Gold Facial', 'Full legs waxing', 'Full arms waxing', 'Spa Pedicure', 'Spa Manicure'],
      },
    ],
    whatIncluded: [
      'Sealed single-use product sachets (L’Oréal, O3+, Cheryl’s)',
      '100% disposable bedsheets, gloves, and wooden spatulas',
      'Post-service cleanup with zero mess left behind',
      'Complimentary consultation by licensed cosmetologists',
    ],
    whatExcluded: [
      'Chemical hair smoothening / rebonding',
    ],
    whyChoose: [
      'Rigorous 10-step sterilization protocol',
      'No waiting in salon queues',
      'Experienced beauticians background verified by police',
    ],
    faqs: [
      {
        question: 'Are the products genuine and authentic?',
        answer: 'Yes! All cosmetics are delivered in manufacturer-sealed mono-dosages and opened right in front of you.',
      },
      {
        question: 'What do I need to prepare in my room?',
        answer: 'Just a quiet room with a fan/AC and power socket. The professional brings the portable stool, disposable sheets, wax heaters, and disposables.',
      },
    ],
  },
  {
    id: 'srv-electrician-visit',
    slug: 'electrician-on-demand',
    name: 'Electrician On-Demand & Diagnostics',
    categoryId: 'cat-electrician',
    categoryName: 'Electrician & Wirecraft',
    rating: 4.85,
    reviewsCount: 9700,
    startingPrice: 199,
    originalPrice: 299,
    durationMin: 30,
    image: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Fan installation, socket repair, short circuit diagnosis, switchboard replacements & MCB tripping fixes.',
    description: 'Got a sparked socket, tripping MCB, or need a chandelier mounted? Our licensed electricians arrive with multi-meters, drills, and standard copper wiring to fix all electrical faults safely.',
    popular: true,
    trending: false,
    recommendedReason: 'Quickest doorstep response time in under 45 minutes',
    variants: [
      {
        id: 'var-elec-diag',
        name: 'Inspection & Minor Fix (Up to 30 mins)',
        price: 199,
        originalPrice: 299,
        durationMin: 30,
        description: 'Diagnostic visit for wiring checks, single switch/socket replacement, or bulb holder repair.',
        included: ['Inspection fee included', 'Diagnostic testing', 'Minor connection fixes'],
      },
      {
        id: 'var-elec-fan',
        name: 'Ceiling Fan Installation / Uninstallation',
        price: 249,
        originalPrice: 399,
        durationMin: 35,
        description: 'Mounting of ceiling fan on hook, regulator wiring, and balancing test.',
        included: ['Bracket assembly', 'Wiring connection', 'Safety balance test'],
      },
      {
        id: 'var-elec-mcb',
        name: 'Distribution Board / Inverter Connection',
        price: 499,
        originalPrice: 799,
        durationMin: 60,
        description: 'Inverter battery setup, MCB change, or high-load appliance socket wiring.',
        included: ['Load calculation', 'Phase testing', 'Heavy duty terminal crimping'],
      },
    ],
    whatIncluded: [
      'Safety check with voltage tester and insulated tools',
      'Fixing of reported electrical issue',
      'Clean drill dust cleanup',
      '30-day warranty on workmanship',
    ],
    whatExcluded: [
      'Cost of replacement switches, wires, or MCBs (billed on actual MRP)',
    ],
    whyChoose: [
      'Certified and licensed electricians only',
      'Zero surprise billing with transparent rate cards',
      'Complimentary earthing check for household appliances',
    ],
    faqs: [
      {
        question: 'Can the electrician purchase parts for me?',
        answer: 'Yes! The electrician can procure ISI-marked switches or wires from authorized neighborhood retailers and provide the purchase receipt.',
      },
    ],
  },
  {
    id: 'srv-sofa-cleaning',
    slug: 'sofa-carpet-shampooing',
    name: 'Sofa & Upholstery Deep Shampooing',
    categoryId: 'cat-cleaning',
    categoryName: 'Cleaning & Pest Control',
    rating: 4.89,
    reviewsCount: 11200,
    startingPrice: 699,
    originalPrice: 999,
    durationMin: 70,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    shortDesc: '3-stage dry vacuum, injection foam shampoo, and moisture extraction to eliminate stains & mites.',
    description: 'Give your living room couch a fresh, hygienic makeover. Removes tea/coffee stains, dust mites, pet hair, and musty odors using German high-suction extractors.',
    popular: false,
    trending: true,
    recommendedReason: 'Frequently booked with Home Cleaning for weekend home refreshes',
    variants: [
      {
        id: 'var-sofa-3',
        name: '3-Seater Fabric Sofa Shampooing',
        price: 699,
        originalPrice: 999,
        durationMin: 60,
        description: 'Deep extraction shampooing for a 3-seater fabric sofa.',
        included: ['Dry vacuum', 'Stain spot treatment', 'Foam brush shampoo', 'Suction moisture extraction'],
      },
      {
        id: 'var-sofa-5',
        name: '5-Seater (3+1+1 or L-Shape) Sofa',
        price: 999,
        originalPrice: 1499,
        durationMin: 90,
        description: 'Complete cleansing for 5 seating seats including cushions.',
        included: ['All seats and backrests', '5 complimentary cushions', 'Deodorization treatment'],
      },
    ],
    whatIncluded: [
      'Industrial dry vacuuming to remove deep-seated particles',
      'Non-hazardous chemical shampoo spray',
      'Gentle mechanical agitation for stubborn stains',
      'High-power moisture extraction (dries within 3-4 hours)',
    ],
    whatExcluded: [
      'Faded fabric color restoration',
      'Torn fabric patchwork',
    ],
    whyChoose: [
      'Removes 98% of deep fabric allergens & pet odors',
      'Quick drying formulation allows couch usage in just a few hours',
    ],
    faqs: [
      {
        question: 'How long will the sofa take to dry?',
        answer: 'Our extraction machine sucks out 90% of the moisture. In a room with ceiling fan running, the sofa will be 100% dry within 3 to 4 hours.',
      },
    ],
  },
  {
    id: 'srv-plumbing-tap',
    slug: 'plumbing-tap-leakage-fix',
    name: 'Tap, Mixer & Drain Pipe Repair',
    categoryId: 'cat-plumber',
    categoryName: 'Plumbing Solutions',
    rating: 4.81,
    reviewsCount: 8400,
    startingPrice: 149,
    originalPrice: 249,
    durationMin: 30,
    image: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Dripping tap fixes, internal washer replacement, kitchen sink waste pipe unclogging & angle valves.',
    description: 'Stop annoying water drips and wasteful leaks. Our plumbers carry washers, Teflon seals, spindle cartridges, and pipe wrenches to resolve kitchen and bathroom plumbing issues rapidly.',
    popular: false,
    trending: false,
    variants: [
      {
        id: 'var-plumb-tap',
        name: 'Tap / Angle Valve Replacement or Repair',
        price: 149,
        originalPrice: 249,
        durationMin: 30,
        description: 'Fixing 1 leaking tap, changing cartridge spindle or fitting a new angle stop cock.',
        included: ['Dismantling fitting', 'Spindle / washer fix', 'Pressure leak test'],
      },
      {
        id: 'var-plumb-sink',
        name: 'Kitchen Sink Waste Pipe & Trap Cleaning',
        price: 249,
        originalPrice: 399,
        durationMin: 40,
        description: 'Clearing greasy food debris blockages from kitchen sink bottle trap or drain pipe.',
        included: ['Trap unscrewing', 'Debris flush', 'New rubber ring installation'],
      },
    ],
    whatIncluded: [
      'Thorough inspection of water pressure lines',
      'Disassembly, cleaning of aerators and replacement of worn washers',
      'Teflon thread sealing to eliminate pinhole leaks',
    ],
    whatExcluded: [
      'Excavation of underground piping',
    ],
    whyChoose: [
      'Prevents water wastage and water seepage behind walls',
      'Experienced in premium Jaquar, Hindware, and Grohe fittings',
    ],
    faqs: [
      {
        question: 'What if the tap needs a new brass spindle?',
        answer: 'The plumber will show you the worn internal part and provide a genuine brass spindle replacement with clear pricing before fitting.',
      },
    ],
  },
  {
    id: 'srv-pest-control',
    slug: 'cockroach-pest-control',
    name: 'Herbal Cockroach & Pest Shield',
    categoryId: 'cat-cleaning',
    categoryName: 'Cleaning & Pest Control',
    rating: 4.87,
    reviewsCount: 7600,
    startingPrice: 799,
    originalPrice: 1199,
    durationMin: 45,
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=80',
    shortDesc: '100% odorless herbal gel paste applied in kitchen cabinets + drain spray to eradicate cockroaches.',
    description: 'No need to empty your kitchen cabinets or leave your house! Our CIB-approved odorless gel is applied in tiny target dots in cabinet hinges, drawers, and behind refrigerators, targeting the nesting colony.',
    popular: true,
    trending: false,
    recommendedReason: 'Essential quarterly pest shield for disease-free kitchens',
    variants: [
      {
        id: 'var-pest-1bhk',
        name: '1-2 BHK Herbal Gel Treatment',
        price: 799,
        originalPrice: 1199,
        durationMin: 45,
        description: 'Complete odorless gel application across kitchen, bathrooms, and living area.',
        included: ['Kitchen cabinet gel bait', 'Sink drain treatment', 'Behind fridge & microwave dots', '60-day warranty'],
      },
      {
        id: 'var-pest-3bhk',
        name: '3-4 BHK Comprehensive Gel + Spray',
        price: 1199,
        originalPrice: 1799,
        durationMin: 70,
        description: 'Large apartment pest shield with complimentary drain foaming.',
        included: ['All rooms gel baiting', 'Balcony & shaft barrier spray', 'Cockroach nest elimination', '90-day warranty'],
      },
    ],
    whatIncluded: [
      'Bayer Maxforce / synthetic pyrethroid odorless dots',
      'No requirement to vacate home or empty kitchen utensils',
      'Safe for infants, elderly family members, and pets',
      'Complimentary retreat within 60 days if pests reappear',
    ],
    whatExcluded: [
      'Bed bug thermal treatment (available as specialized service)',
    ],
    whyChoose: [
      'Zero pungent chemical smell',
      'Targets cockroach colonies via domino effect',
      '60-day service guarantee',
    ],
    faqs: [
      {
        question: 'Do I need to wash all kitchen utensils after the treatment?',
        answer: 'No! Because we do not use aerosol pesticide sprays, your utensils and food grains remain completely untouched and safe.',
      },
    ],
  },
  {
    id: 'srv-mens-grooming',
    slug: 'mens-salon-grooming',
    name: 'Gentlemen’s Haircut & Beard Styling',
    categoryId: 'cat-beauty',
    categoryName: 'Beauty & Salon',
    rating: 4.9,
    reviewsCount: 13400,
    startingPrice: 299,
    originalPrice: 499,
    durationMin: 40,
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Custom fade haircut, hot towel beard sculpting, scalp massage & face detan at your doorstep.',
    description: 'Experience salon perfection without waiting in line at the barbershop. Our master stylists bring professional clippers, single-use neck strips, sanitized scissors, and floor mats.',
    popular: true,
    trending: true,
    variants: [
      {
        id: 'var-men-haircut',
        name: 'Men’s Stylish Haircut + Wash Consultation',
        price: 299,
        originalPrice: 499,
        durationMin: 35,
        description: 'Scissor & clipper precision cut + hair styling product application.',
        included: ['Consultation', 'Haircut', 'Neck shave with disposable blade', 'Floor cleanup'],
      },
      {
        id: 'var-men-combo',
        name: 'Haircut + Beard Trim + Charcoal Face Detan',
        price: 599,
        originalPrice: 999,
        durationMin: 65,
        description: 'Complete grooming package for weekends or meetings.',
        included: ['Haircut', 'Sharp beard trim', 'Activated charcoal detan pack', 'Head acupressure massage'],
      },
    ],
    whatIncluded: [
      'Freshly sterilized tools with UV box and alcohol spray',
      'Single-use disposable cape and floor sheet',
      'Mess-free post-cut vacuuming',
    ],
    whatExcluded: [
      'Permanent hair straightening',
    ],
    whyChoose: [
      '100% hygienic with disposable blades for every client',
      'Top-rated stylists from premium salon chains',
    ],
    faqs: [
      {
        question: 'Will cut hair scatter on my floor?',
        answer: 'The barber spreads a wide waterproof floor cape beneath your chair and sweeps up every hair strand into a disposable bag after finishing.',
      },
    ],
  },
  {
    id: 'srv-appliance-washing-machine',
    slug: 'washing-machine-refrigerator-repair',
    name: 'Washing Machine & Refrigerator Repair',
    categoryId: 'cat-appliance-repair',
    categoryName: 'Appliance Repair',
    rating: 4.88,
    reviewsCount: 6540,
    startingPrice: 299,
    originalPrice: 499,
    durationMin: 45,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Motor vibration, spin tub issue, cooling leakage & PCB repair with 30-day warranty.',
    description: 'Expert diagnostic testing for top-load, front-load washing machines, frost-free and single door refrigerators of all major brands.',
    popular: true,
    trending: true,
    variants: [
      {
        id: 'var-appliance-diag',
        name: 'Comprehensive Diagnostic Visit',
        price: 299,
        originalPrice: 499,
        durationMin: 45,
        description: 'Multi-meter circuit check, motor test and quote before repair.',
        included: ['Diagnostics visit', 'Defect identification', 'Standard quote for parts'],
      },
    ],
    whatIncluded: [
      'Complete mechanical and electrical inspection',
      'Original spare parts estimate on MRP',
      '30-day post-service warranty',
    ],
    whatExcluded: ['Cost of spare parts or replacement PCB'],
    whyChoose: ['Certified appliance engineers', 'Zero hidden fees'],
    faqs: [
      {
        question: 'How quickly can the technician arrive?',
        answer: 'Technicians typically arrive within 45-60 minutes across all serviced cities.',
      },
    ],
  },
  {
    id: 'srv-water-purifier-ro',
    slug: 'ro-water-purifier-service',
    name: 'RO Water Purifier Service & Filter Replacement',
    categoryId: 'cat-water-purifier',
    categoryName: 'Water Purifier',
    rating: 4.91,
    reviewsCount: 8200,
    startingPrice: 399,
    originalPrice: 599,
    durationMin: 40,
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Complete TDS water quality test, sediment/carbon filter flush & leakage seal.',
    description: 'Protect your family with certified drinking water servicing. We test inlet and outlet TDS and check UV/UF membrane integrity.',
    popular: true,
    trending: false,
    variants: [
      {
        id: 'var-ro-service',
        name: 'Standard RO Maintenance Check',
        price: 399,
        originalPrice: 599,
        durationMin: 40,
        description: 'TDS calibration, pipe descaling and booster pump pressure test.',
        included: ['TDS testing', 'Pre-filter clean', 'Booster pressure check'],
      },
    ],
    whatIncluded: ['TDS testing before and after service', 'Sanitization of storage tank'],
    whatExcluded: ['Cost of replacement RO membrane or sediment filters'],
    whyChoose: ['Certified water lab grade testing instruments', 'Compatible with Kent, Aquaguard, Pureit'],
    faqs: [
      {
        question: 'What TDS level is safe for drinking?',
        answer: 'WHO and BIS suggest TDS below 300 ppm with optimal essential minerals is ideal.',
      },
    ],
  },
  {
    id: 'srv-laptop-electronics',
    slug: 'laptop-desktop-repair-service',
    name: 'Laptop & Electronics On-Site Repair',
    categoryId: 'cat-laptop-electronics',
    categoryName: 'Laptop & Electronics',
    rating: 4.86,
    reviewsCount: 5120,
    startingPrice: 349,
    originalPrice: 549,
    durationMin: 50,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Slow performance tune-up, thermal paste re-application, RAM upgrade & screen fix.',
    description: 'Doorstep computer hardware & software diagnostics. Get SSD upgrades, virus removal and hardware replacements performed right in front of your eyes.',
    popular: false,
    trending: true,
    variants: [
      {
        id: 'var-laptop-diag',
        name: 'Doorstep Hardware & Software Check',
        price: 349,
        originalPrice: 549,
        durationMin: 50,
        description: 'Complete diagnostic check for boot issues, thermal overheating or keyboard failure.',
        included: ['Diagnostic scan', 'Thermal test', 'On-spot estimate'],
      },
    ],
    whatIncluded: ['Data privacy assurance — no drive cloning without permission', 'Standard rates'],
    whatExcluded: ['Hardware replacement parts cost'],
    whyChoose: ['Repairs done in your presence', 'Experienced chip-level technicians'],
    faqs: [
      {
        question: 'Is my personal data safe during the repair?',
        answer: 'Yes! All repairs are performed in front of you without accessing confidential folders.',
      },
    ],
  },
  {
    id: 'srv-home-improvement-interiors',
    slug: 'home-improvement-fixtures',
    name: 'Home Improvement & Modern Lighting Installation',
    categoryId: 'cat-home-improvement',
    categoryName: 'Home Improvement',
    rating: 4.93,
    reviewsCount: 4280,
    startingPrice: 499,
    originalPrice: 799,
    durationMin: 60,
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    shortDesc: 'Curtain rod mounting, track lights, mirror hangings, wall shelving & accent fittings.',
    description: 'Transform your living spaces with expert mounting and aesthetic home improvements. We bring laser levels and masonry anchors for clean wall installs.',
    popular: true,
    trending: true,
    variants: [
      {
        id: 'var-home-upgrade-pack',
        name: 'Living Room Makeover Installation (Up to 3 Items)',
        price: 499,
        originalPrice: 799,
        durationMin: 60,
        description: 'Mounting of curtains, decorative mirrors or artwork with laser alignment.',
        included: ['Laser leveling', 'Heavy duty anchors', 'Cleanup'],
      },
    ],
    whatIncluded: ['High-precision laser drill alignment', 'Wall dust vacuuming'],
    whatExcluded: ['Supply of custom mirrors or heavy artworks'],
    whyChoose: ['Flawless alignment without wall cracks', 'Verified interior craftsmen'],
    faqs: [
      {
        question: 'Do you bring wall anchors and screws?',
        answer: 'Yes, our craftsmen carry heavy duty nylon anchors, brass screws, and Fischer plugs.',
      },
    ],
  },
];

export const COUPONS = [
  {
    code: 'WELCOME150',
    discountType: 'FLAT',
    value: 150,
    minBookingAmount: 399,
    description: 'Flat ₹150 OFF on your first Service Assist service booking',
    expiry: '2026-12-31',
    maxUsesPerCustomer: 1,
  },
  {
    code: 'CLEAN10',
    discountType: 'PERCENTAGE',
    value: 10,
    minBookingAmount: 500,
    maxDiscount: 200,
    description: '10% OFF on all Cleaning & Pest Control services',
    expiry: '2026-10-30',
    categoryIds: ['cat-cleaning', 'cat-bathroom-cleaning', 'cat-sofa-cleaning', 'cat-pest-control'],
  },
  {
    code: 'SALON200',
    discountType: 'FLAT',
    value: 200,
    minBookingAmount: 799,
    description: 'Flat ₹200 OFF on premium salon at home packages',
    expiry: '2026-11-15',
    categoryIds: ['cat-beauty'],
  },
  {
    code: 'WEEKEND50',
    discountType: 'FLAT',
    value: 50,
    minBookingAmount: 299,
    description: '₹50 instant cash discount for weekend slots',
    expiry: '2026-12-31',
  },
  {
    code: 'FESTIVE300',
    discountType: 'FLAT',
    value: 300,
    minBookingAmount: 1299,
    description: 'Flat ₹300 OFF on full home service combos over ₹1299',
    expiry: '2026-12-31',
  },
];
