export const publicUser = (u) => ({
  id: u.id,
  name: u.name,
  email: u.email,
  phone: u.phone,
  role: u.role,
  avatar: u.profileImage,
  addresses: u.addresses || [],
  createdAt: u.createdAt,
});
export const serviceInclude = {
  category: true,
  variants: true,
  _count: { select: { items: { where: { booking: { review: { isNot: null } } } } } },
};
export const serviceView = (s) => ({
  ...s,
  startingPrice: Number(s.startingPrice),
  categoryName: s.category.name,
  durationMin: s.duration,
  reviewsCount: s._count?.items || 0,
  variants: s.variants.map((v) => ({
    ...v,
    price: Number(v.price),
    originalPrice: v.originalPrice == null ? undefined : Number(v.originalPrice),
  })),
});
export const professionalInclude = {
  user: { select: { name: true, profileImage: true } },
  services: true,
  availability: true,
  _count: { select: { reviews: true, bookings: { where: { status: 'COMPLETED' } } } },
};
export const professionalView = (p) => ({
  id: p.id,
  name: p.user.name,
  avatar: p.user.profileImage,
  businessName: p.businessName,
  profession: p.businessName,
  bio: p.description,
  description: p.description,
  experienceYears: p.experience,
  experience: p.experience,
  verified: p.verificationStatus === 'VERIFIED',
  verificationStatus: p.verificationStatus,
  serviceAreas: p.serviceArea,
  serviceArea: p.serviceArea,
  categoryId: p.services[0]?.categoryId,
  serviceIds: p.services.map((s) => s.id),
  services: p.services,
  rating: p.rating,
  reviewsCount: p._count?.reviews || 0,
  completedJobs: p._count?.bookings || 0,
  isAvailableToday: p.isAvailableToday,
  availability: p.availability,
  skills: p.services.map((s) => s.name),
  certifications: [],
  languages: [],
  availableDays: [],
  workingHours: 'See availability',
});
export const bookingInclude = {
  customer: { select: { id: true, name: true, phone: true, email: true } },
  professional: { include: { user: { select: { name: true, phone: true, profileImage: true } } } },
  service: true,
  address: true,
  items: { include: { service: { include: serviceInclude }, variant: true } },
  payment: true,
  history: { orderBy: { timestamp: 'asc' } },
};
// Customers and professionals must never receive each other's phone number or e-mail address:
// they communicate through in-app chat. Only administrators (support/safety) see contact details.
export function bookingView(b, role) {
  const contactVisible = role === 'ADMIN';
  return {
    id: b.id,
    bookingNumber: b.id,
    customerId: b.customerId,
    userId: b.customerId,
    userName: b.customer.name,
    customerName: b.customer.name,
    userPhone: contactVisible ? b.customer.phone : undefined,
    customerPhone: contactVisible ? b.customer.phone : undefined,
    userEmail: contactVisible ? b.customer.email : undefined,
    professionalId: b.professionalId,
    professionalName: b.professional?.user.name || 'Awaiting assignment',
    professionalPhone: contactVisible ? b.professional?.user.phone : undefined,
    professionalAvatar: b.professional?.user.profileImage,
    serviceId: b.serviceId,
    serviceName: b.service.name,
    serviceSlug: b.service.slug,
    serviceImage: b.service.image,
    address: b.addressSnapshot,
    date: b.bookingDate.toISOString().slice(0, 10),
    scheduledDate: b.bookingDate.toISOString().slice(0, 10),
    timeSlot: b.bookingTime,
    scheduledTimeSlot: b.bookingTime,
    status: b.status,
    statusHistory: b.history,
    total: Number(b.totalAmount),
    subtotal: Number(b.subtotal),
    discount: Number(b.discount),
    taxes: Number(b.taxes),
    tax: Number(b.taxes),
    paymentMethod: b.payment?.paymentMethod,
    paymentStatus: b.payment?.status,
    specialInstructions: b.notes,
    instructions: b.notes,
    couponCode: b.couponCode,
    createdAt: b.createdAt,
    verificationOtp: role === 'CUSTOMER' ? b.verificationOtp : undefined,
    items: b.items.map((i) => ({
      service: serviceView(i.service),
      variant: { ...i.variant, name: i.name, price: Number(i.unitPrice) },
      quantity: i.quantity,
    })),
  };
}
